version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: blog-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./blog-api
    container_name: blog-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/blogDB?authSource=admin
    depends_on:
      - mongodb

  frontend:
    build: ./blog-web
    container_name: blog-frontend
    ports:
      - "4200:80" # Maps Docker's port 80 to host's 4200 so existing URLs keep working seamlessly
    depends_on:
      - backend

volumes:
  mongodb_data:
