import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { BlogService, BlogEntry } from '../../core/services/blog.service';

@Component({
  selector: 'app-blog-add',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './blog-add.component.html',
  styleUrl: './blog-add.component.css'
})
export class BlogAddComponent {
  title = '';
  author = '';
  category = '';
  description = '';
  hashtag = '';
  commentsAllowed = true;
  textContent = '';
  images: {name: string, dataUrl: string}[] = [];

  constructor(private blogService: BlogService, private router: Router) {}

  onFileChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length) {
      for (let i = 0; i < input.files.length; i++) {
        const file = input.files[i];
        const reader = new FileReader();
        reader.onload = () => {
          this.images.push({
            name: file.name,
            dataUrl: reader.result as string
          });
        };
        reader.readAsDataURL(file);
      }
    }
  }

  removeImage(index: number) {
    this.images.splice(index, 1);
  }

  onSubmit() {
    if (!this.title || !this.author || !this.category || !this.description) {
      alert('Please fill out the required fields (Title, Author, Category, Description).');
      return;
    }

    // Build final content with embedded base64 images
    let finalContent = this.textContent;
    if (this.images.length > 0) {
      finalContent += '<div class="inserted-images">';
      for (const img of this.images) {
        finalContent += `<img src="${img.dataUrl}" alt="${img.name}" />`;
      }
      finalContent += '</div>';
    }

    const newEntry: BlogEntry = {
      id: '', // Will be generated by service
      title: this.title,
      author: this.author,
      description: this.description,
      creationDate: new Date(),
      editDates: [],
      impressionCount: 0,
      content: finalContent,
      commentsAllowed: this.commentsAllowed,
      imagesCount: this.images.length,
      comments: [],
      category: this.category,
      hashtag: this.hashtag
    };

    this.blogService.addOrUpdateEntry(newEntry);
    this.router.navigate(['/']);
  }
}
